/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.CreateUser;
import model.Login;
import model.UserHistory;

/**
 *
 * @author anzal
 */
public  class AdminJFrame extends javax.swing.JFrame  {

    /**
     * Creates new form AdminJFrame
     */
    
    Login login;
    UserHistory history;
    CreateUser user1;
    //UserAccountHistory historyaccount;
    
    public AdminJFrame() {
        initComponents();
        
        login = new Login();
        history = new UserHistory();
        user1 = new CreateUser();
       // historyaccount = new UserAccountHistory();
        //btnViewUserDetails.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPaneAdmin = new javax.swing.JSplitPane();
        controlPanelAdmin = new javax.swing.JPanel();
        btnCreateuser = new javax.swing.JButton();
        btnViewUser = new javax.swing.JButton();
        btnSignout = new javax.swing.JButton();
        btnUserLogin = new javax.swing.JButton();
        workAreaAdmin = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlPanelAdmin.setBackground(new java.awt.Color(204, 255, 255));

        btnCreateuser.setBackground(new java.awt.Color(0, 0, 0));
        btnCreateuser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCreateuser.setForeground(new java.awt.Color(204, 255, 255));
        btnCreateuser.setText("Create User");
        btnCreateuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateuserActionPerformed(evt);
            }
        });

        btnViewUser.setBackground(new java.awt.Color(0, 0, 0));
        btnViewUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnViewUser.setForeground(new java.awt.Color(204, 255, 255));
        btnViewUser.setText("View/Search User");
        btnViewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewUserActionPerformed(evt);
            }
        });

        btnSignout.setBackground(new java.awt.Color(0, 0, 0));
        btnSignout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSignout.setForeground(new java.awt.Color(204, 255, 255));
        btnSignout.setText("Sign Out");
        btnSignout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignoutActionPerformed(evt);
            }
        });

        btnUserLogin.setBackground(new java.awt.Color(0, 0, 0));
        btnUserLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUserLogin.setForeground(new java.awt.Color(204, 255, 255));
        btnUserLogin.setText("User Login");
        btnUserLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserLoginMouseClicked(evt);
            }
        });
        btnUserLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelAdminLayout = new javax.swing.GroupLayout(controlPanelAdmin);
        controlPanelAdmin.setLayout(controlPanelAdminLayout);
        controlPanelAdminLayout.setHorizontalGroup(
            controlPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateuser)
                    .addComponent(btnViewUser)
                    .addComponent(btnUserLogin)
                    .addGroup(controlPanelAdminLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnSignout)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlPanelAdminLayout.setVerticalGroup(
            controlPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelAdminLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(btnCreateuser)
                .addGap(18, 18, 18)
                .addComponent(btnViewUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(btnUserLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSignout)
                .addGap(124, 124, 124))
        );

        splitPaneAdmin.setLeftComponent(controlPanelAdmin);

        workAreaAdmin.setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon("C:\\Users\\anzal\\OneDrive - Northeastern University\\Documents\\NetBeansProjects\\Assignment_2\\src\\Images\\images.jpeg"))); // NOI18N
        workAreaAdmin.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                workAreaAdminComponentHidden(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButton1.setText("ADMIN ACTIONS");

        javax.swing.GroupLayout workAreaAdminLayout = new javax.swing.GroupLayout(workAreaAdmin);
        workAreaAdmin.setLayout(workAreaAdminLayout);
        workAreaAdminLayout.setHorizontalGroup(
            workAreaAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        workAreaAdminLayout.setVerticalGroup(
            workAreaAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
        );

        splitPaneAdmin.setRightComponent(workAreaAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPaneAdmin)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPaneAdmin)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateuserActionPerformed
        
        
        
        
        try {
            // TODO add your handling code here:
            
            CreateUserJPanel user = new CreateUserJPanel(history);
            splitPaneAdmin.setRightComponent(user);
        } catch (SQLException ex) {
            Logger.getLogger(AdminJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_btnCreateuserActionPerformed

    private void btnSignoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignoutActionPerformed
        // TODO add your handling code here:
        
        dispose();
        
    }//GEN-LAST:event_btnSignoutActionPerformed

    private void btnViewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewUserActionPerformed
        try {
            // TODO add your handling code here:
            
            ViewUserJPanel view = new ViewUserJPanel(history);
            splitPaneAdmin.setRightComponent(view);
        } catch (SQLException ex) {
            Logger.getLogger(AdminJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnViewUserActionPerformed

    private void btnUserLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserLoginActionPerformed
        // TODO add your handling code here:
        
        UserLoginPage  user = new UserLoginPage(login,history);
        splitPaneAdmin.setRightComponent(user);
        
    }//GEN-LAST:event_btnUserLoginActionPerformed

    private void btnUserLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserLoginMouseClicked
        // TODO add your handling code here:
        
        btnUserLogin.setVisible(true);
        //btnViewUserDetails.setVisible(true);
        
    }//GEN-LAST:event_btnUserLoginMouseClicked

    private void workAreaAdminComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_workAreaAdminComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_workAreaAdminComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminJFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateuser;
    private javax.swing.JButton btnSignout;
    private javax.swing.JButton btnUserLogin;
    private javax.swing.JButton btnViewUser;
    private javax.swing.JPanel controlPanelAdmin;
    private javax.swing.JButton jButton1;
    private javax.swing.JSplitPane splitPaneAdmin;
    private javax.swing.JPanel workAreaAdmin;
    // End of variables declaration//GEN-END:variables
}
