/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Login;


/**
 *
 * @author anzal
 */
public class AdminLoginPage extends javax.swing.JPanel {

    /**
     * Creates new form AdminLoginPage
     */
    
    Login login;
    
    public AdminLoginPage(Login login) {
        initComponents();
        
        this.login = login;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lbladminUsername = new javax.swing.JLabel();
        lbladminPassword = new javax.swing.JLabel();
        txtadminUsername = new javax.swing.JTextField();
        btnadminLogin = new javax.swing.JButton();
        txtadminPassword = new javax.swing.JPasswordField();

        setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon("C:\\Users\\anzal\\OneDrive - Northeastern University\\Documents\\NetBeansProjects\\Assignment_2\\src\\Images\\images.jpeg"))); // NOI18N

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("ADMIN LOGIN");

        lbladminUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbladminUsername.setText("Username : ");

        lbladminPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbladminPassword.setText("Password : ");

        txtadminUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtadminUsernameActionPerformed(evt);
            }
        });

        btnadminLogin.setBackground(new java.awt.Color(0, 0, 0));
        btnadminLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnadminLogin.setForeground(new java.awt.Color(255, 0, 0));
        btnadminLogin.setText("Login");
        btnadminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadminLoginActionPerformed(evt);
            }
        });

        txtadminPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtadminPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbladminPassword)
                        .addGap(18, 18, 18)
                        .addComponent(txtadminPassword))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbladminUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtadminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btnadminLogin)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(lblTitle)
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbladminUsername)
                    .addComponent(txtadminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbladminPassword)
                    .addComponent(txtadminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnadminLogin)
                .addGap(266, 266, 266))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtadminUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtadminUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtadminUsernameActionPerformed

   // MainJFrame jframe = new MainJFrame();
    //jframe.setDefaultCloseOperation(MainJFrame.EXIT_ON_CLOSE);
    
    private void btnadminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadminLoginActionPerformed
        // TODO add your handling code here:
        
        String username = txtadminUsername.getText();
        String username_predefined = "admin";
        String password = String.valueOf(txtadminPassword.getPassword());
        String password_predefined = "admin";
       

      
        if(username.equals(username_predefined) && (password.equals(password_predefined))){
            
            JOptionPane.showMessageDialog(this, "Succcessfully logged in");
          
       txtadminPassword.setText(null);
       txtadminUsername.setText(null);
       AdminJFrame admin = new AdminJFrame();
       admin.setVisible(true);
       admin.setSize(1600, 940);
      
        }
        else{
            JOptionPane.showMessageDialog(this, "Wrong Username or Password ", "Error", JOptionPane.ERROR_MESSAGE);
             }
        
    }//GEN-LAST:event_btnadminLoginActionPerformed

   
    
    private void txtadminPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtadminPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtadminPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadminLogin;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lbladminPassword;
    private javax.swing.JLabel lbladminUsername;
    private javax.swing.JPasswordField txtadminPassword;
    private javax.swing.JTextField txtadminUsername;
    // End of variables declaration//GEN-END:variables

   }
