/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.CreateUser;
import model.UserHistory;

/**
 *
 * @author anzal
 */
public class CreateUserJPanel extends javax.swing.JPanel {  
    
    Connection con;
    ResultSet rs;
    PreparedStatement pst;
    
    /**
     * Creates new form CreateUser
     */
    
    UserHistory history;
    
    public CreateUserJPanel(UserHistory history) throws SQLException {
      
            initComponents(); 
            this.history = history;
            ComboEnabled.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Enabled","Disabled"}));
            
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CreateUserJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
            con  = DriverManager.getConnection("jdbc:mysql://localhost:3306/assignment2","root","root");
            pst = con.prepareStatement("select * from user");
            
            rs = pst.executeQuery();
        
            if(rs.next()){
                txtFname.setText(rs.getString(2));
                txtLname.setText(rs.getString(3));
                txtNeu.setText(rs.getString(1));
                txtAge.setText(rs.getString(4));
                txtAddress.setText(rs.getString(5));
                txtEmail.setText(rs.getString(6));
                txtPhone.setText(rs.getString(7));
                txtPincode.setText(rs.getString(8));
                txtUsername.setText(rs.getString(9));
                txtPassword.setText(rs.getString(10));
                ComboEnabled.setSelectedItem(rs.getStatement());
                      
            }
            
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblFname = new javax.swing.JLabel();
        lblLname = new javax.swing.JLabel();
        lblNeu = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblPincode = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtFname = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        txtNeu = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtPincode = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblStatus = new javax.swing.JLabel();
        ComboEnabled = new javax.swing.JComboBox<>();

        setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon("C:\\Users\\anzal\\OneDrive - Northeastern University\\Documents\\NetBeansProjects\\Assignment_2\\src\\Images\\123.jpg"))); // NOI18N

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("CREATE USER");
        lblTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblFname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFname.setText("First Name :");

        lblLname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLname.setText("Last Name :");
        lblLname.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        lblNeu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNeu.setText("NEU ID :");

        lblAge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAge.setText("Age : ");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmail.setText("Email : ");

        lblPhone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPhone.setText("Phone : ");

        lblPincode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPincode.setText("Pincode : ");

        lblAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAddress.setText("Address : ");

        btnSave.setBackground(new java.awt.Color(204, 255, 255));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUsername.setText("Username : ");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPassword.setText("Password : ");

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblStatus.setText("Status : ");

        ComboEnabled.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enabled", "Disabled" }));
        ComboEnabled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboEnabledActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPincode, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNeu, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLname, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFname, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFname)
                            .addComponent(txtLname)
                            .addComponent(txtNeu)
                            .addComponent(txtAge)
                            .addComponent(txtEmail)
                            .addComponent(txtPhone)
                            .addComponent(txtPincode)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername)
                            .addComponent(lblPassword)
                            .addComponent(lblStatus))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(ComboEnabled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(287, 287, 287))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFname)
                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLname)
                    .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNeu)
                    .addComponent(txtNeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPincode)
                    .addComponent(txtPincode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(ComboEnabled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave)
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            // TODO add your handling code here:
            
            //Integer temp = null;
            String fname = txtFname.getText();
            String lname = txtLname.getText();
            
            int neu = Integer.parseInt(txtNeu.getText());
           // String neu1 = Integer.toString(neu); 
            int age = Integer.parseInt(txtAge.getText());
            //String age1 = Integer.toString(age);
            
            String address = txtAddress.getText();
            
            String email = txtEmail.getText();
            
            int phone  = Integer.parseInt(txtPhone.getText());
            //String phone1 = Integer.toString(phone);
            
            int pincode  = Integer.parseInt(txtPincode.getText());
            //String pincode1 = Integer.toString(pincode);
            
            String username = txtUsername.getText();
            String password = String.valueOf(txtPassword.getPassword());
            String status = ComboEnabled.getSelectedItem().toString();
            
            CreateUser cu = history.addNewUser();
            pst = con.prepareStatement("insert into user(neu_id,first_name,last_name,age,address,email,phone,pincode,username,password,status)values(?,?,?,?,?,?,?,?,?,?,?)");
            
            
            if (containsOnlyLetters(fname) && isEmptyValue(fname)) {
                    cu.setFname(fname);
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid input for First name: ", "Error", JOptionPane.ERROR_MESSAGE);
                }
            
            if (containsOnlyLetters(lname) && isEmptyValue(lname)) {
                    cu.setLname(lname);
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid input for Last name: ", "Error", JOptionPane.ERROR_MESSAGE);
                }
            
            
            
                cu.setNeu_id(neu);
          
            
            

                cu.setAge(age);
            
            
            
            
            
            
            if (isValidEmail(email) && isEmptyValue(email)) {
                    cu.setEmail(email);
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid input for Email: ", "Error", JOptionPane.ERROR_MESSAGE);
                }
            
            
            if (isEmptyValue(address)) {
                    cu.setAddress(address);
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid input for Address: ", "Error", JOptionPane.ERROR_MESSAGE);
                }
            
            
            
            
                cu.setPhone(phone);
             
            
            
            
            
                cu.setPincode(pincode);
            
            
            
            
            if (isEmptyValue(username)) {
                    cu.setUsername(username);
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid input for Username: ", "Error", JOptionPane.ERROR_MESSAGE);
                }
            
            
             if (isEmptyValue(password)) {
                    cu.setPassword(password);
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid input for Password: ", "Error", JOptionPane.ERROR_MESSAGE);
                }
            
            
             if (isEmptyValue(status)) {
                    cu.setStatus(status);
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid input for Status: ", "Error", JOptionPane.ERROR_MESSAGE);
                }
             
            
            
            
            pst.setString(1, txtNeu.getText());
            pst.setString(2, txtFname.getText());
            pst.setString(3, txtLname.getText());
            pst.setString(4, txtAge.getText());
            pst.setString(5, txtAddress.getText());
            pst.setString(6, txtEmail.getText());
            pst.setString(7, txtPhone.getText());
            pst.setString(8, txtPincode.getText());
            pst.setString(9, txtUsername.getText());
            pst.setString(10, String.valueOf(txtPassword.getPassword()));
            pst.setString(11, ComboEnabled.getSelectedItem().toString());
            pst.executeUpdate();
    
            JOptionPane.showMessageDialog(this, "New User Created");
            
            
        } catch (SQLException ex) {
            Logger.getLogger(CreateUserJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            txtFname.setText(null);
            txtLname.setText(null);
            txtNeu.setText(null);
            txtAge.setText(null);
            txtEmail.setText(null);
            txtAddress.setText(null);
            txtPhone.setText(null);
            txtPincode.setText(null);
            txtUsername.setText(null);
            txtPassword.setText(null);
            
        
    }//GEN-LAST:event_btnSaveActionPerformed

    
     private static boolean isEmptyValue(String name) {
        return !name.isEmpty();
    }
    
     
     private static boolean isValidNumber(String number) {
        String regex = "^[0-9]*$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(number);

        return matcher.matches();
    }
     
     private boolean containsOnlyLetters(String name) {
                return name.matches("^[a-zA-Z]*$");
            }
     
     private static boolean isValidEmail(String email1) {
        String reg = "^[A-Za-z0-9+_.-]+@(.+)$";
        Pattern pattern = Pattern.compile(reg);
        Matcher matcher = pattern.matcher(email1);

        return matcher.matches();
    }
     
     private static boolean isValidPhoneNumber(String phone) {
        String regex = "^[0-9\\-\\s]+$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(phone);

        return matcher.matches();
    }
    
    
    
    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void ComboEnabledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboEnabledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboEnabledActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboEnabled;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFname;
    private javax.swing.JLabel lblLname;
    private javax.swing.JLabel lblNeu;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPincode;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtNeu;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPincode;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
