/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import model.CreateUser;
import model.UserHistory;

/**
 *
 * @author anzal
 */
public class UserLandingPageJPanel extends javax.swing.JPanel {

    
    Connection con;
    ResultSet rs;
    PreparedStatement pst;
    
    /**
     * Creates new form UserLandingPageJPanel
     */
    
    UserHistory history;
    private CreateUser loguser;
    
    private ArrayList<String> passwordHistory = new ArrayList<>();
    private JPasswordField newPasswordField;
    
    public UserLandingPageJPanel(UserHistory history,CreateUser user1) throws Exception {
        
            initComponents();
            
            newPasswordField = new JPasswordField(20);
            
            this.history = history;
            this.loguser = user1; 
            //tblUser.setVisible(false);
            
            txtNeu.setText(String.valueOf(loguser.getNeu_id()));
            txtFname.setText(loguser.getFname());
            txtLname.setText(loguser.getLname());
            txtAge.setText(String.valueOf(loguser.getAge()));
            txtAddress.setText(loguser.getAddress());
            txtEmail.setText(loguser.getEmail());
            txtPhone.setText(String.valueOf(loguser.getPhone()));
            txtPincode.setText(String.valueOf(loguser.getPincode()));
            txtUsername.setText(loguser.getUsername());
            txtPassword.setText(loguser.getPassword());
            ComboEnabled.setSelectedItem(loguser.getStatus());
            
            
            
          /*  Class.forName("com.mysql.cj.jdbc.Driver");
            con  = DriverManager.getConnection("jdbc:mysql://localhost:3306/assignment2","root","root");
            pst = con.prepareStatement("select * from user");
            
            rs = pst.executeQuery();
        
            if(rs.next()){
                txtFname.setText(rs.getString(2));
                txtLname.setText(rs.getString(3));
                txtNeu.setText(rs.getString(1));
                txtAge.setText(rs.getString(4));
                txtAddress.setText(rs.getString(5));
                txtEmail.setText(rs.getString(6));
                txtPhone.setText(rs.getString(7));
                txtPincode.setText(rs.getString(8));
                txtUsername.setText(rs.getString(9));
                txtPassword.setText(rs.getString(10));
                      
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UserLandingPageJPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(UserLandingPageJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblTitlepersonalinfo = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblPincode = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        txtPincode = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        lblFname = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        btnUpdateUser = new javax.swing.JButton();
        lblNeu = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        txtNeu = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblLname = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        lblTitlepersonalinfo1 = new javax.swing.JLabel();
        btnUpdateUserAccount = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        ComboEnabled = new javax.swing.JComboBox<>();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUsername.setText("Username : ");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPassword.setText("Password : ");

        lblTitlepersonalinfo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitlepersonalinfo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitlepersonalinfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitlepersonalinfo.setText("USER'S PERSONAL INFORMATION");
        lblTitlepersonalinfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPhone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPhone.setText("Phone : ");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblPincode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPincode.setText("Pincode : ");

        lblAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAddress.setText("Address : ");

        lblFname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFname.setText("First Name :");

        btnUpdateUser.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdateUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateUser.setForeground(new java.awt.Color(204, 255, 255));
        btnUpdateUser.setText("Update User");
        btnUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserActionPerformed(evt);
            }
        });

        lblNeu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNeu.setText("NEU ID :");

        lblAge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAge.setText("Age : ");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmail.setText("Email : ");

        lblLname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLname.setText("Last Name :");

        lblTitlepersonalinfo1.setBackground(new java.awt.Color(255, 255, 255));
        lblTitlepersonalinfo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitlepersonalinfo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitlepersonalinfo1.setText("USER'S ACCOUNT INFORMATION");
        lblTitlepersonalinfo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnUpdateUserAccount.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdateUserAccount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateUserAccount.setForeground(new java.awt.Color(204, 255, 255));
        btnUpdateUserAccount.setText("Update User Account");
        btnUpdateUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserAccountActionPerformed(evt);
            }
        });

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblStatus.setText("Status : ");

        ComboEnabled.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enabled", "Disabled" }));
        ComboEnabled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboEnabledActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitlepersonalinfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(280, 280, 280))
            .addGroup(layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(btnUpdateUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatus)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(ComboEnabled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNeu)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                            .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                                        .addComponent(lblPassword))
                                    .addComponent(lblUsername))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(btnUpdateUserAccount))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPincode, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPincode, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(310, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(125, 125, 125)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNeu, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblLname, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblFname, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(797, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 797, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTitlepersonalinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(126, 126, 126)))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAddress, txtAge, txtEmail, txtFname, txtLname, txtNeu, txtPassword, txtPhone, txtPincode, txtUsername});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPincode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPincode)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblTitlepersonalinfo1)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsername))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPassword)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateUserAccount)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(ComboEnabled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnUpdateUser)
                .addContainerGap(189, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(lblTitlepersonalinfo)
                    .addGap(33, 33, 33)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFname)
                        .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lblLname)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lblNeu)
                    .addGap(12, 12, 12)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblAge)
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(388, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAddress, txtAge, txtEmail, txtFname, txtLname, txtNeu, txtPassword, txtPhone, txtPincode, txtUsername});

    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserActionPerformed
        // TODO add your handling code here:

       int neu =Integer.parseInt(txtNeu.getText());
       String fname = txtFname.getText();
       String lname = txtLname.getText();
       int age   = Integer.parseInt(txtAge.getText());
       String address = txtAddress.getText();
       String email = txtEmail.getText();
       int phone = Integer.parseInt(txtPhone.getText());
       int pincode = Integer.parseInt(txtPincode.getText());
       String status = ComboEnabled.getSelectedItem().toString();
       //String username = txtUsername.getText();
       //String password = txtPassword.getText();
        
       
       CreateUser user2 = new CreateUser();
       user2.setNeu_id(neu);
       user2.setFname(fname);
       user2.setLname(lname);
       user2.setAge(age);
       user2.setAddress(address);
       user2.setEmail(email);
       user2.setPhone(phone);
       user2.setPincode(pincode);
       user2.setStatus(status);
      // user2.setUsername(username);
       //user2.setPassword(password);
       
       
       
      // CreateUser user1 = new CreateUser();
       //user1.setUsername(username);
       //user1.setPassword(password);
       
       ArrayList<CreateUser> users = history.getHistory();
       
       for(CreateUser user3 : users){
           if(user3.getFname().equals(fname))
           {
               
        user3.setNeu_id(neu);
       user3.setFname(fname);
       user3.setLname(lname);
       user3.setAge(age);
       user3.setAddress(address);
       user3.setEmail(email);
       user3.setPhone(phone);
       user3.setPincode(pincode);
       user3.setStatus(status);
       //user3.setUsername(username);
       //user3.setPassword(password);  
       break;
       }
              
                 }
       
       JOptionPane.showMessageDialog(this, "User updated successfully");
               

       

        /*model.setRowCount(0);
        int i = tblUser.getSelectedRow();
        c
        model.setValueAt(txtFname.getText(), i, 1);
        model.setValueAt(txtLname.getText(), i, 2);
        model.setValueAt(txtAge.getText(), i, 3);
        model.setValueAt(txtAddress.getText(), i, 4);
        model.setValueAt(txtEmail.getText(), i, 5);
        model.setValueAt(txtPhone.getText(), i, 6);
        model.setValueAt(txtPincode.getText(), i, 7);
        */

    }//GEN-LAST:event_btnUpdateUserActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnUpdateUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserAccountActionPerformed
        // TODO add your handling code here:
        
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        
        String newPassword = new String(txtPassword.getText());
        
        CreateUser user2 = new CreateUser();
       user2.setUsername(username);
       //user2.setPassword(password);
        
       
       ArrayList<CreateUser> users4 = history.getHistory();
       
       for(CreateUser user3 : users4){
           if(user3.getUsername().equals(username))
           {
               
    
       user3.setUsername(username);
       //user3.setPassword(password);  
       break;
       }
              
                 }
       
       JOptionPane.showMessageDialog(this, "User Account updated successfully");
               
       
       
        if (isNewPasswordValid(newPassword)) {
                    passwordHistory.add(newPassword);
                    //txtPassword.setText("");
                    JOptionPane.showMessageDialog(this, "Password updated successfully.");
                    
                    for(CreateUser user3 : users4){
           if(user3.getUsername().equals(username))
           {
               
    
       //user3.setUsername(username);
       user3.setPassword(password);  
       break;
       }
              
                 }
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Password is already used. Please choose a new one.");
                    
                    
                    
                }
        //newPasswordField.setText("");
    }//GEN-LAST:event_btnUpdateUserAccountActionPerformed

    private void ComboEnabledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboEnabledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboEnabledActionPerformed

    
    private boolean isNewPasswordValid(String newPassword) {
        // Check if the new password is not in the history
        for (String oldPassword : passwordHistory) {
            if (newPassword.equals(oldPassword)) {
                return false; // Password is already used
            }
        }
        return true; // Password is valid
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboEnabled;
    private javax.swing.JButton btnUpdateUser;
    private javax.swing.JButton btnUpdateUserAccount;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFname;
    private javax.swing.JLabel lblLname;
    private javax.swing.JLabel lblNeu;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPincode;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitlepersonalinfo;
    private javax.swing.JLabel lblTitlepersonalinfo1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtNeu;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPincode;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
