/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Container;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import model.CreateUser;
import model.Login;
import model.UserHistory;

/**
 *
 * @author anzal
 */
public class UserLoginPage extends javax.swing.JPanel {

    /**
     * Creates new form UserLoginPage
     */
    
    Login login;
   // UserAccountHistory historyaccount;
    UserHistory history;
    CreateUser user1;
    
    public UserLoginPage(Login login,UserHistory history) {
        initComponents();
        
        this.login = login;
        //this.historyaccount = historyaccount;
        this.history = history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lbluserUsername = new javax.swing.JLabel();
        lbluserPassword = new javax.swing.JLabel();
        txtuserUsername = new javax.swing.JTextField();
        txtuserPassword = new javax.swing.JPasswordField();
        btnuserLogin = new javax.swing.JButton();

        setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon("C:\\Users\\anzal\\OneDrive - Northeastern University\\Documents\\NetBeansProjects\\Assignment_2\\src\\Images\\images.jpeg"))); // NOI18N

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("USER LOGIN PAGE");
        lblTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbluserUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbluserUsername.setText("Username : ");

        lbluserPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbluserPassword.setText("Password : ");

        btnuserLogin.setBackground(new java.awt.Color(0, 0, 0));
        btnuserLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnuserLogin.setForeground(new java.awt.Color(204, 255, 255));
        btnuserLogin.setText("Login");
        btnuserLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuserLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbluserPassword)
                        .addGap(18, 18, 18)
                        .addComponent(txtuserPassword))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbluserUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtuserUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btnuserLogin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtuserPassword, txtuserUsername});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lblTitle)
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbluserUsername)
                    .addComponent(txtuserUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbluserPassword)
                    .addComponent(txtuserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnuserLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtuserPassword, txtuserUsername});

    }// </editor-fold>//GEN-END:initComponents

    private void btnuserLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuserLoginActionPerformed
        // TODO add your handling code here:
        
         if (txtuserUsername.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Please enter the username");
    } else if (txtuserPassword.getPassword().length == 0) {
        JOptionPane.showMessageDialog(null, "Please enter the password");
    } else {
        
         boolean credentialsMatch = false;
         String enteredusername = txtuserUsername.getText();
        String enteredpassword = String.valueOf(txtuserPassword.getPassword()); 
        String enabled = "Enabled";
        //String disabled = "Disabled";

        for (CreateUser user : history.getHistory()) {
            if (user.getUsername().equals(enteredusername) && user.getPassword().equals(enteredpassword) && user.getStatus().equals(enabled) ) {
                credentialsMatch = true;
                break;
            }
        }
        
            if (credentialsMatch) {
                
           JOptionPane.showMessageDialog(null, "Login Successful");
                 
                 
                 CreateUser user1 =null;
                 
                 for(CreateUser user : history.getHistory()){
                     if(user.getUsername().equals(enteredusername) && user.getPassword().equals(enteredpassword)) {
                         user1 = user;
                //credentialsMatch = true;
                break;
                 }
                 }
                 
                 if(user1 != null){
                 
                     try {
                         UserLandingPageJPanel land = new UserLandingPageJPanel(history,user1);
                         
                         Container  parentContainer = this.getParent();
                         
                         if (parentContainer instanceof JSplitPane) {
                             JSplitPane splitPane = (JSplitPane) parentContainer;
                             
                             splitPane.setRightComponent(null);
                             splitPane.setRightComponent(land);
                         }   } catch (Exception ex) {
                         Logger.getLogger(UserLoginPage.class.getName()).log(Level.SEVERE, null, ex);
                     }
                 
                 
                 }
                            
            }
            
            
            else{
                     JOptionPane.showMessageDialog(null, "Wrong username or password or User is blocked!", "Message", JOptionPane.ERROR_MESSAGE);
                 } 
 
    }
        
    }//GEN-LAST:event_btnuserLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnuserLogin;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lbluserPassword;
    private javax.swing.JLabel lbluserUsername;
    private javax.swing.JPasswordField txtuserPassword;
    private javax.swing.JTextField txtuserUsername;
    // End of variables declaration//GEN-END:variables
}
